---
version: "2"
plugins:
  shellcheck:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-1-50-2
  reek:
    enabled: true
exclude_patterns:
- config/
- db/
- test/
- vendor/
- .idea/
