shared: &shared
  kubernetes: <%= ENV.fetch('DISABLE_K8S_ROUTES_CREATION', '0') == '0' %>
  kubernetes_force_native_ingress: <%= ActiveModel::Type::Boolean.new.cast(ENV['FORCE_NATIVE_INGRESS']) %>
  kubernetes_ingress_class: <%= ENV.fetch('INGRESS_CLASS', 'nginx') %>

production:
  <<: *shared

development:
  <<: *shared

test:
  <<: *shared
  