example:
  attributes:
    # see other properties in https://www.keycloak.org/docs-api/3.4/javadocs/org/keycloak/representations/idm/ClientTemplateRepresentation.html
    standardFlowEnabled: true
    implicitFlowEnabled: false
    serviceAccountsEnabled: true
    directAccessGrantsEnabled: true

default: &default
  http_client:
    connect_timeout: 3
    send_timeout: 3
    receive_timeout: 3

development:

production:
  <<: *default

test:
