apiVersion: v1
kind: Template
metadata:
  name: zync-secrets
objects:
- apiVersion: v1
  stringData:
    BUGSNAG_API_KEY: "${BUGSNAG_API_KEY}"
    DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_URL}:${DB_PORT}/${DB_NAME}"
    SECRET_KEY_BASE: "${SECRET_KEY_BASE}" 
    SKYLIGHT_AUTHENTICATION: "${SKYLIGHT_AUTHENTICATION}"
    ZYNC_AUTHENTICATION_TOKEN: "${ZYNC_AUTHENTICATION_TOKEN}"
  kind: Secret
  metadata:
    name: zync
  type: Opaque

parameters:
- name: BUGSNAG_API_KEY
  description: Bugsnag API key
  required: true
- name: DB_URL
  description: The name of openshift service connecting to Postgres server
  required: true
- name: DB_NAME
  description: The Name of the database to be used in Postgres
  required: true
- name: DB_USER
  description: Database User
  required: true
- name: DB_PASSWORD
  description: Database Password
  required: true
- name: DB_PORT
  description: Database Port
  required: true
- name: SECRET_KEY_BASE
  description: Secret Key base
  required: true
- name: SKYLIGHT_AUTHENTICATION
  description: Skylight Authentication
  required: true
- name: ZYNC_AUTHENTICATION_TOKEN
  description: Zync authentication token
  required: true

