apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: zync
  name: ruby-25-ubi7
spec:
  tags:
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi7/ruby-25
    name: latest
    referencePolicy:
      type: Source
