apiVersion: v1
kind: Template
metadata:
  name: zync-deploymentconfig
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: zync
    name: zync
  spec:
    replicas: 2
    selector:
      app: zync
      deploymentconfig: zync
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          prometheus.io/port: "9393"
          prometheus.io/scrape: "true"
        labels:
          app: zync
          deploymentconfig: zync
      spec:
        containers:
        - env:
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: RAILS_ENV
            value: production
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: DATABASE_URL
                name: zync
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                key: SECRET_KEY_BASE
                name: zync
          - name: BUGSNAG_API_KEY
            valueFrom:
              secretKeyRef:
                key: BUGSNAG_API_KEY
                name: zync
          - name: SKYLIGHT_AUTHENTICATION
            valueFrom:
              secretKeyRef:
                key: SKYLIGHT_AUTHENTICATION
                name: zync
          - name: ZYNC_AUTHENTICATION_TOKEN
            valueFrom:
              secretKeyRef:
                key: ZYNC_AUTHENTICATION_TOKEN
                name: zync
          - name: RAILS_MAX_THREADS
            value: '10'
          - name: RAILS_LOG_LEVEL
            value: info
          image: zync:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          name: zync
          ports:
          - name: zync
            containerPort: 8080
            protocol: TCP
          - name: metrics
            containerPort: 9393
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 250M
          terminationMessagePath: /dev/termination-log
        - env:
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: RAILS_ENV
            value: production
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: DATABASE_URL
                name: zync
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                key: SECRET_KEY_BASE
                name: zync
          - name: BUGSNAG_API_KEY
            valueFrom:
              secretKeyRef:
                key: BUGSNAG_API_KEY
                name: zync
          - name: SKYLIGHT_AUTHENTICATION
            valueFrom:
              secretKeyRef:
                key: SKYLIGHT_AUTHENTICATION
                name: zync
          - name: ZYNC_AUTHENTICATION_TOKEN
            valueFrom:
              secretKeyRef:
                key: ZYNC_AUTHENTICATION_TOKEN
                name: zync
          - name: RAILS_LOG_LEVEL
            value: info
          args:
          - que
          - --worker-count
          - 10
          image: zync:latest
          imagePullPolicy: Always
          name: que
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 250M
          terminationMessagePath: /dev/termination-log
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - zync
        from:
          kind: ImageStreamTag
          name: zync:latest
      type: ImageChange
