apiVersion: v1
kind: Template
metadata:
  name: zync-route
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: zync
    name: zync
  spec:
    host: "{$HOST}"
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: zync
      weight: 100
    wildcardPolicy: None

parameters:
- name: HOST
  description: Zync Route Host
  required: true
