apiVersion: v1
kind: List
items:
  - apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      annotations:
        autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":28,"currentAverageValue":"0"}}]'
      labels:
        app: zync
      name: zync-puma
    spec:
      maxReplicas: 5
      minReplicas: 2
      scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: DeploymentConfig
        name: zync-puma
      targetCPUUtilizationPercentage: 65
  - apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      annotations:
        autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":28,"currentAverageValue":"0"}}]'
      labels:
        app: zync
      name: zync-que
    spec:
      maxReplicas: 5
      minReplicas: 2
      scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: DeploymentConfig
        name: zync-que
      targetCPUUtilizationPercentage: 65
